#!/bin/bash
# build 
#
while getopts "" opt; do
    case $opt in
	\?)
	    echo "Invalid option: -$OPTARG" >&2
	    ;;
    esac
done
if [[ "$#" -ne 0 ]]; then
    echo "Illegal number of parameters" >&2
    exit 1
fi

export IMG_NAME=${IMG_NAME:-'myblog'}
export CONTAINER_NAME=${CONTAINER_NAME:-"${IMG_NAME}_running"}
export HOST_PORT=${HOST_PORT:-'4000'}

docker remove "$CONTAINER_NAME"
docker build -t "$IMG_NAME" .
