#!/bin/bash
# build_and_run.sh 
#
while getopts "" opt; do
    case $opt in
	\?)
	    echo "Invalid option: -$OPTARG" >&2
	    ;;
    esac
done
if [[ "$#" -ne 0 ]]; then
    echo "Illegal number of parameters" >&2
    exit 1
fi

export IMG_NAME='myblog'
export CONTAINER_NAME="${IMG_NAME}_running"
export HOST_PORT='4000'

docker remove "$CONTAINER_NAME" 2> /dev/null
docker build -f docker/dev.dockerfile -t "$IMG_NAME:dev" .
#docker run --name "$CONTAINTER_NAME" "$IMG_NAME"
docker run -it -t \
    -p 127.0.0.1:$HOST_PORT:4000 \
    --name "$CONTAINTER_NAME" "$IMG_NAME:dev"
